apiVersion: apps/v1
kind: Deployment
metadata:
  name: iks-vpc
  labels:
    app: iks-vpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iks-vpc
  template:
    metadata:
      labels:
        app: iks-vpc
    spec:
      containers:
        - name: iks-vpc
          image: uk.icr.io/logdna-poc/iks-vpc:latest
          resources:
            requests:
              memory: "320Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
              cpu: "200m"
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: iks-vpc
  labels:
    app: iks-vpc
spec:
  ports:
    - port: 9080
  type: ClusterIP
  selector:
    app: iks-vpc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iks-vpc
spec:
  tls:
    - hosts:
        - HOST
      secretName: cfs-logdna-mule-0bbc0fd82a5c7a8402ba5d809e331a82-0000 
  rules:
    - host: cfs-logdna-mule-0bbc0fd82a5c7a8402ba5d809e331a82-0000.eu-gb.containers.appdomain.cloud
      http:
        paths:
          - path: /autoscale-webapp
            backend:
              serviceName: iks-vpc
              servicePort: 9080
